#Creating a range of tensors and tensors-like

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.1.0+cu121


In [ ]:
# use torch.range()
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes
Note :Tensor is one of the 3 big errors you will run into pytorch & deep learning
#####1.Tensors are not right datatype
#####2.tensors  mot right shape
#####3.tensors not on the right device
Precision in computing:
https://en.wikipedia.org/wiki/Precision_(computer_science)


In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,# what datatype is the tensor
                               device=None,# what device is your tensor on
                               requires_grad=False)# whether or mot to track gradience with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### getting information from tensor
1.Tensors are not right datatype - to do  get datatype from a tensor, can use tensor.dtype
2.tensors mot right shape- to get shape from a tensor, can use tensor.shape
3.tensors not on the right device- to get device from a tensor, can use tensor.device

In [ ]:
#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.3157, 0.8281, 0.9583, 0.2686],
        [0.9207, 0.4648, 0.9405, 0.8464],
        [0.4678, 0.4087, 0.8156, 0.8086]])

In [ ]:
# find out details about tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.size}")
print(f"Device tensor is on  : {some_tensor.device}")

tensor([[0.3157, 0.8281, 0.9583, 0.2686],
        [0.9207, 0.4648, 0.9405, 0.8464],
        [0.4678, 0.4087, 0.8156, 0.8086]])
Datatype of tensor:torch.float32
Shape of tensor : <built-in method size of Tensor object at 0x78c6d796eca0>
Device tensor is on  : cpu


###manipulate tensors (tensor operation)
Tensor operation include:
* Addition
* Substitution
* Multiplication
* Division
* Matrix Multiplication

In [ ]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor+=10

In [ ]:
# multiply tensor by 10
tensor*10

tensor([110, 120, 130])

In [ ]:
tensor

tensor([11, 12, 13])

In [ ]:
# substract 10
tensor - 10

tensor([1, 2, 3])

In [ ]:
# Try out Pytorch in-built Function
torch.mul(tensor,10)

tensor([110, 120, 130])

In [ ]:
torch.add(tensor,10)

tensor([21, 22, 23])


# matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning
1. Element-wise multiplication
2. Matrix multiplication (dot product)
more information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

the important things to notice is:
the inner dimensions must be match. EX (2,3) and(3,2)
and the resultant matrix will be outer dimensions. output of above example (2,2)




In [ ]:
#element wise multiplication
import time
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([11, 12, 13]) * tensor([11, 12, 13])
Equals:tensor([121, 144, 169])


In [ ]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(434)

In [ ]:
tensor

tensor([11, 12, 13])

In [ ]:
#matrix multiplying by hand
1*1+ 2*2+3*3

14

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(434)
CPU times: user 2.71 ms, sys: 0 ns, total: 2.71 ms
Wall time: 2.73 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 114 µs, sys: 0 ns, total: 114 µs
Wall time: 119 µs


tensor(434)

In [ ]:
# we can also use "@" for matrix multiplication
tensor @ tensor
#torch.mm(tensor,tensor)

tensor(434)

one of the most common errors in deep learning: shape errors

In [ ]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,4]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
#torch.mm(tensor_A,tensor_B) torch.mm is the sa,e as torch.matmul(it's an alias for)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues ,we can manipulate the shape of one of our tensors using a transpose.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T,tensor_B.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([3, 2]))

In [ ]:
# matrix multiplication operation works when tensor_B is transposed
print(f"original shapes:tensor_A={tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"New shapes:tensor_A={tensor_A.shape}(same shape as above),tensor_B.T={tensor_B.T.shape}")
print(f"Multiplying :{tensor_A.shape} @ {tensor_B.shape}<- inner dimensions must match")
print("Output:\n")

output=torch.matmul(tensor_A, tensor_B.T)
print(f"\n output shape:{output.shape}")

original shapes:tensor_A=torch.Size([3, 2]),tensor_B=torch.Size([3, 2])
New shapes:tensor_A=torch.Size([3, 2])(same shape as above),tensor_B.T=torch.Size([2, 3])
Multiplying :torch.Size([3, 2]) @ torch.Size([3, 2])<- inner dimensions must match
Output:


 output shape:torch.Size([3, 3])


**Finding the min,max, mean, sum etc(tensor aggregation)**

In [ ]:
#create a tensor
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
# find the mean-note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Finding the position in tensor that has the minimum value with argmin()--> returns index position of target where the minimum value occurs
x.argmin()

tensor(0)

In [49]:
x.argmax()

tensor(9)

Reshaping, stacking, squeezing and unsqueezing tensors

1.   Reshaping- reshapes an input tensor to defined shapeList item
2.   View - return a view of an input
tensor of certain shape but keep the same memory as the original tensor
3.   stacking - combines multiple tensors on top of each other(Vstack) or side by side(hstack)
4.   Squeeze- removes all 1 dimensions from a tensor
unsqueeze-






### Reshaping, stacking, squeezing and unsqueezing
To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |

In [50]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [51]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [52]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [53]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [54]:
# if we wanted to stack our new tensor on top of itself five times, we could do so with torch.stack().#

In [55]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [56]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [57]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [58]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


#Indexing (selecting data from tensors)
Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [59]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
#Indexing values goes outer dimension -> inner dimension (check out the square brackets).
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [61]:
#You can also use : to specify "all values in this dimension" and then use a comma (,) to add another dimension.
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [62]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [64]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

Indexing can be quite confusing to begin with, especially with larger tensors (I still have to try indexing multiple times to get it right). But with a bit of practice and following the data explorer's motto (visualize, visualize, visualize), you'll start to get the hang of it.

## PyTorch tensors & NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.  

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor.
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.

In [65]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Note: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

However, many PyTorch calculations default to using float32.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).

Because we reassigned tensor above, if you change the tensor, the array stays the same.

In [66]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [67]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [68]:
#And the same rule applies as above, if you change the original tensor, the new numpy_tensor stays the same.
#Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))