#Creating a range of tensors and tensors-like

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.1.0+cu121


In [4]:
# use torch.range()
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes
Note :Tensor is one of the 3 big errors you will run into pytorch & deep learning
#####1.Tensors are not right datatype
#####2.tensors  mot right shape
#####3.tensors not on the right device
Precision in computing:
https://en.wikipedia.org/wiki/Precision_(computer_science)


In [6]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,# what datatype is the tensor
                               device=None,# what device is your tensor on
                               requires_grad=False)# whether or mot to track gradience with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [7]:
float_32_tensor.dtype

torch.float32

In [8]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [9]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### getting information from tensor
1.Tensors are not right datatype - to do  get datatype from a tensor, can use tensor.dtype
2.tensors mot right shape- to get shape from a tensor, can use tensor.shape
3.tensors not on the right device- to get device from a tensor, can use tensor.device

In [10]:
#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.3042, 0.6729, 0.2329, 0.4898],
        [0.3801, 0.1141, 0.3230, 0.8006],
        [0.1828, 0.7278, 0.4332, 0.6523]])

In [11]:
# find out details about tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.size}")
print(f"Device tensor is on  : {some_tensor.device}")

tensor([[0.3042, 0.6729, 0.2329, 0.4898],
        [0.3801, 0.1141, 0.3230, 0.8006],
        [0.1828, 0.7278, 0.4332, 0.6523]])
Datatype of tensor:torch.float32
Shape of tensor : <built-in method size of Tensor object at 0x7cb17d524540>
Device tensor is on  : cpu


###manipulate tensors (tensor operation)
Tensor operation include:
* Addition
* Substitution
* Multiplication
* Division
* Matrix Multiplication

In [12]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor+=10

In [13]:
# multiply tensor by 10
tensor*10

tensor([110, 120, 130])

In [14]:
tensor

tensor([11, 12, 13])

In [15]:
# substract 10
tensor - 10

tensor([1, 2, 3])

In [16]:
# Try out Pytorch in-built Function
torch.mul(tensor,10)

tensor([110, 120, 130])

In [17]:
torch.add(tensor,10)

tensor([21, 22, 23])


# matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning
1. Element-wise multiplication
2. Matrix multiplication (dot product)
more information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html




In [18]:
#element wise multiplication
import time
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([11, 12, 13]) * tensor([11, 12, 13])
Equals:tensor([121, 144, 169])


In [19]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(434)

In [20]:
tensor

tensor([11, 12, 13])

In [21]:
#matrix multiplying by hand
1*1+ 2*2+3*3

14

In [22]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(434)
CPU times: user 351 µs, sys: 1.6 ms, total: 1.96 ms
Wall time: 6.05 ms


In [23]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 86 µs, sys: 16 µs, total: 102 µs
Wall time: 107 µs


tensor(434)

In [26]:
# we can also use "@" for matrix multiplication
tensor @ tensor
#torch.mm(tensor,tensor)

tensor(434)