This is Strating of Pytorch learning, First we have to import the required libraries in the code


In [ ]:

import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.1.0+cu121


#Introduction to Tensors
###creating tensors
pytorch sensors are created using 'torch.sensor'=https://pytorch.org/docs/stable/tensors.html

In [ ]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back python int
scalar.item()

7

In [ ]:
#vector
vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim #no.of square brackets

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
 [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
#shape means it will give there's 1 dimension of 3 by 3
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]])

###Random Tensors
Why random tensors ?

Random tensors are imp beacause the way many neural netwuorks  is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

start with random numbers-->look at the data --> update the random numbers --> look at the data --> update the random tensors

Torch random sensors=https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
#create a random tensor of size (3,4)
random_tensor=torch.rand(1,3,4)
random_tensor

tensor([[[0.7255, 0.4452, 0.4248, 0.0140],
         [0.2761, 0.1595, 0.0370, 0.7965],
         [0.2284, 0.9901, 0.0298, 0.5792]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
#create a random_tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))  # red green blue
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
torch.rand(3,3)

tensor([[0.4916, 0.3629, 0.0868],
        [0.9498, 0.2735, 0.6731],
        [0.4047, 0.4137, 0.7047]])

#ZEROS and ONES



In [ ]:
#create  a tensor  of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
###creates tensors of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

###create a range of tensors and tensors like

In [ ]:
#use torch.range()
one_to_ten = torch.arange(start=0,end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes
###Note :Tensor is one of the 3 big errors you will run into pytorch & deep learning
####1.Tensors are not right datatype
####2.tensors  mot right shape
####3.tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32